Fix windows error C2440: 'initializing': cannot convert from 'initializer list' to 'std::basic_ofstream<char,std::char_traits<char>>'
(cherry picked from commit 7d4d036cafe5c78873027f94f18e10a6f1e73483)