Fix intermittent windows fatal error C1083: Cannot open include file: 'gen-cpp/OmniSci.h': No such file or directory when building LockMgr/CMakeFiles/LockMgr.dir/LockMgr.cpp.obj.
(cherry picked from commit 6c1c75093f905d8426ae64d690eb25d29be2e73c)