Fix current Windows build errors.
* Fix windows error C2672: 'std::max': no matching overloaded function found
* Fix errors introduced by #include <windows.h>.
* Fix windows error C2039: 'GetObject': is not a member of 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>'
* Fix winsock/winsock2 incompatibility.
* Fix windows fatal error LNK1104: cannot open file 'optimized.lib'
* Fix windows error LNK2038: mismatch detected for 'boost_log_abi': value 'v2_mt_nt6' doesn't match value 'v2_mt_nt62' in initdb.cpp.obj
* Fix missing gdal-config error on windows.
* Fix windows error C2332: 'class': missing tag name
* Fix windows error C2039: 'random_shuffle': is not a member of 'std'
* Fix windows fatal error C1083: Cannot open include file: 'gen-cpp/OmniSci.h': No such file or directory when building Catalog/CMakeFiles/Catalog.dir/Catalog.cpp.obj.